### ISSUE TITLE
Export image PNG

### ISSUE THREAD

**Issue by robinsonjra** [mlnc21/PowerApps-SVG-Merge-Modul#2]
It is possible to export the image to png

**Comment by mlnc21** [comment]
Hi @robinsonjra,
You can use a Third-party Connector to convert the SVG to other image types.

**Comment by robinsonjra** [comment]
> Hi @robinsonjra, You can use a Third-party Connector to convert the SVG to other image types.

I have tried with different connectors as pages (Ejm: https://svgtopng.com/) and they cannot convert the svg generated with this plugin.

**Comment by mlnc21** [comment]
![image](https://github.com/mlnc21/PowerApps-SVG-Merge-Modul/assets/80674540/86df60fe-42fc-43ea-babb-b76857ce88f7)


Try to use Power Automate with the "Convert File" from OneDrive. 😊
![image](https://github.com/mlnc21/PowerApps-SVG-Merge-Modul/assets/80674540/2dc9e162-906f-4ac7-88f3-ca70d357d83c)

**Comment by robinsonjra** [comment]
![image](https://github.com/mlnc21/PowerApps-SVG-Merge-Modul/assets/24886832/cb2b51b8-31d1-4e41-bc10-b9a5ec976637)

is correct that it converts it but the end result is a blank square.

**Comment by mlnc21** [comment]
Good Morning @robinsonjra ,

I ve checked the Behavior and i found out, a <Image> Type inside an SVG is not convertible.
I will Check a alternate Workaround.

[Check: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image)

**Comment by mlnc21** [comment]
HI @robinsonjra ,

Check out the new Version 2.1.0

Now you can Convert the SVG to any other Formats 💯🫡
