### ISSUE TITLE
Output property GenerateTextImage need to be Text instead of Boolean

### ISSUE THREAD

**Issue by legendgod** [mlnc21/PowerApps-SVG-Merge-Modul#4]
v2.1

**Comment by mlnc21** [comment]
Hi @legendgod ,
Microsoft add new Updates on Custom Components.
you can resolve this in 2 ways.
1. Disable RetiredFeature
 open the App and go to Settings > Updates > Retired and Disable "Disable component behavior property return type check"
![image](https://github.com/user-attachments/assets/565f7fac-7ce3-44d1-aac7-2447534004e4)

2. Use IfError around the Actions to return type check
![image](https://github.com/user-attachments/assets/bb9f1a82-a4dd-4144-8b71-5d4f75519c8c)
